package io.github.thiagocesar1.api.rest.erros;

public class PedidoNaoEncontradoException extends RuntimeException{

	public PedidoNaoEncontradoException() {
		super("Pedido n√£o encontrado!");
	}
	
	

}
